# Generated by Django 2.0.3 on 2018-04-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelTicket',
            fields=[
                ('travel_ticket_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('travel_from_city', models.CharField(max_length=100)),
                ('travel_to_city', models.CharField(max_length=100)),
                ('travel_price', models.IntegerField()),
            ],
        ),
    ]
