# Generated by Django 2.0.3 on 2018-04-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_travelticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelTicket',
            fields=[
                ('hotel_ticket_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('hotel_name', models.CharField(max_length=100)),
                ('hotel_city', models.CharField(max_length=100)),
                ('hotel_room_type', models.CharField(max_length=100)),
                ('hotel_price', models.IntegerField()),
            ],
        ),
    ]
