# Generated by Django 2.0.3 on 2018-04-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_hotelticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightTicket',
            fields=[
                ('flight_ticket_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('flight_name', models.CharField(max_length=50)),
                ('flight_from_city', models.CharField(max_length=100)),
                ('flight_to_city', models.CharField(max_length=100)),
                ('flight_price', models.IntegerField()),
            ],
        ),
    ]
