# Generated by Django 2.0.3 on 2018-04-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_flightticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_arrival_date', models.DateTimeField()),
                ('travel_ticket_from_city',models.CharField(max_length=100)),
                ('travel_ticket_to_city',models.CharField(max_length=100)),
                ('travel_no_of_ticket', models.IntegerField()),
                ('travel_ticket_price', models.IntegerField()),
                ('travel_ticket_payment', models.CharField(max_length=10)),
                ('travel_ticket_id', models.ForeignKey(on_delete='true', to='login.TravelTicket')),
                ('user_id', models.ForeignKey(on_delete='true', to='login.Tuser')),
            ],
        ),
    ]
