# Generated by Django 2.0.3 on 2018-04-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_traveluserdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_checkin', models.DateTimeField()),
                ('hotel_no_of_day', models.IntegerField()),
                ('hotel_ticket_name',models.CharField(max_length=100)),
                ('hotel_ticket_city',models.CharField(max_length=100)),
                ('hotel_ticket_room_type',models.CharField(max_length=100)),
                ('hotel_no_of_ticket', models.IntegerField()),
                ('hotel_ticket_price', models.IntegerField()),
                ('hotel_ticket_payment', models.CharField(max_length=10)),
                ('hotel_ticket_id', models.ForeignKey(on_delete='true', to='login.HotelTicket')),
                ('user_id', models.ForeignKey(on_delete='true', to='login.Tuser')),
            ],
        ),
    ]
