# Generated by Django 2.0.3 on 2018-04-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_hoteluserdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_arrival_date', models.DateTimeField()),
                ('flight_no_of_ticket', models.IntegerField()),
                ('flight_ticket_name',models.CharField(max_length=50)),
                ('flight_ticket_from_city',models.CharField(max_length=100)),
                ('flight_ticket_to_city',models.CharField(max_length=100)),
                ('flight_ticket_price', models.IntegerField()),
                ('flight_ticket_payment', models.CharField(max_length=10)),
                ('flight_ticket_id', models.ForeignKey(on_delete='true', to='login.FlightTicket')),
                ('user_id', models.ForeignKey(on_delete='true', to='login.Tuser')),
            ],
        ),
    ]
