# Generated by Django 2.0.3 on 2018-04-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_flightuserdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_ticket_id', models.CharField(max_length=30)),
                ('payment_full_name_on_card', models.CharField(max_length=50)),
                ('Payment_card_type', models.CharField(max_length=30)),
                ('payment_card_number', models.IntegerField()),
                ('payment_amount', models.IntegerField()),
                ('payment_card_expairy_date', models.DateTimeField()),
                ('payment_cvv', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('payment_time', models.TimeField()),
                ('user_id', models.ForeignKey(on_delete='true', to='login.Tuser')),
            ],
        ),
    ]
