# Generated by Django 2.0.3 on 2018-04-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_paymentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('faq_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('faq_name', models.CharField(max_length=30)),
                ('faq_mobileno', models.IntegerField()),
                ('faq_email', models.CharField(max_length=30)),
                ('faq_subject', models.CharField(max_length=100)),
                ('faq_country', models.CharField(max_length=20)),
                ('faq_message', models.CharField(max_length=200)),
            ],
        ),
    ]
