# Generated by Django 2.0.3 on 2018-04-05 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuser',
            old_name='birthdate',
            new_name='bdate',
        ),
        migrations.RenameField(
            model_name='tuser',
            old_name='firstname',
            new_name='phoneno',
        ),
        migrations.RenameField(
            model_name='tuser',
            old_name='lastname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='tuser',
            name='mobileno',
        ),
    ]
